# Generated by Django 3.0 on 2022-03-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('Executive', 'Executive'), ('Suite', 'Suite'), ('Presidential', 'Presidential')], max_length=255, null=True)),
                ('number_of_guests', models.IntegerField(default=0, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
