# Generated by Django 3.0 on 2022-03-24 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='Apartment',
        ),
    ]
