# Generated by Django 3.0 on 2022-03-25 13:13

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20220324_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='Access_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='amneties',
            field=models.CharField(choices=[('Essentials', 'Essentials'), ('Wifi', 'Wifi'), ('TV', 'TV'), ('Heat', 'Heat')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='bedrooms',
            field=models.CharField(choices=[('Studio', 'Studio'), ('Ordinary', 'Ordinary'), ('Officetel', 'Officetel'), ('Penthouse', 'Penthouse')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='beds',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='street_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
