# Generated by Django 3.0 on 2022-03-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20220326_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
