# Generated by Django 3.0 on 2022-03-26 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_auto_20220326_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='neighborhood',
            new_name='apartment',
        ),
    ]
