# Generated by Django 3.0 on 2022-03-26 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_auto_20220326_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mylocal', to='myApp.Apartment'),
        ),
    ]
