# Generated by Django 3.0 on 2022-03-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_auto_20220326_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['location']},
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='apart_location',
            new_name='location',
        ),
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together={('apartment', 'location')},
        ),
    ]
