# Generated by Django 3.0 on 2022-03-26 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_auto_20220326_1910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guests',
            new_name='GuestsRoom',
        ),
        migrations.AddField(
            model_name='apartment',
            name='amnesity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartment_amnesity', to='myApp.Amnesities'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='apart_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartment_location', to='myApp.Location'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='guestroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartment_guestsroom', to='myApp.GuestsRoom'),
        ),
    ]
